
export default [  //沒給名字也行，引入的時候自己給名字
    {
      //總之先把router搞定吧，這是個路由表
      path:'/',
      name:'layout',
      redirect:'/index',
      component:()=>import('@/views/LayOut'),
      children:[
        {
          path:'/index',
          name:'index',
          component:()=>import('@/views/index/Home')
        },
        {
          path:'/orders/list',
          name:'order_list',
          component:()=>import('@/views/orders/OrdersList'),
          meta:{bread:['訂單管理','訂單列表']}
        },
        {
          path:'/waybill/list',
          name:'waybill_list',
          component:()=>import('@/views/wayBill/WayBillList'),
          meta:{bread:['運單管理','運單列表'],keepAlive:true}
        },
        {
          path:'/waybill/list/detail',
          name:'waybill_list_detail',
          component:()=>import('@/views/wayBill/WaybillDetail'),
          meta:{bread:['運單管理','運單列表','運單詳情']}
        },
        {
          path:'/waybill/in',
          name:'waybill_in',
          component:()=>import('@/views/wayBill/WayBillIn'),
          meta:{bread:['運單管理','運單錄入']}
        },
        {
          path:'/depart/data',
          name:'depart_data',
          component:()=>import('@/views/depart/DepartData'),
          meta:{bread:['發車管理','發車數據單']}
        },
        {
          path:'carrier/list',
          name:'carrier_list',
          component:()=>import('@/views/carrier/CarrierList'),
          meta:{bread:['承運商管理','承運商列表']}
        },
        {
          path:'/customer',
          name:'customer',
          component:()=>import('@/views/customer/CustomerIndex'),
          meta:{bread:['客戶管理']}
        },
        {
          path:'/personal',
          name:'personal',
          component:()=>import('@/views/personal/Index')
        }
      ]
    }
    ,
    {
      path:'/login',
      name:'login',
      component:()=>import('@/views/Login')
    }
    ,
    {
      path:'/home',
      name:'hometest',
      component:()=>import('@/views/Home')
    }
    ]